
build-android:
	npx react-native bundle --platform android --dev false --entry-file App.js --bundle-output ./assets/index.android.bundle --assets-dest ./res
	npx eas build -p android --profile preview